### ISSUE TITLE
Incorrect DS.Model relationship attribute naming (?)

### ISSUE THREAD

**Issue by medemas** [andycrum/ember-data-model-maker#13]
Currently, when given the model criteria (specifying DS.ActiveModelAdapter):

**Movement**
name (string)
movement type (string)
records (hasMany)

**Record**
max effort (number)
max type (string)
movement (belongsTo)

I am told to set the model definitions:

```javascript

// app/models/movement.js
export default DS.Model.extend({
  name: DS.attr('string'),
  movementType: DS.attr('string'),
  recordIds: DS.hasMany('record')
});

// app/models/record.js
export default DS.Model.extend({
  maxEffort: DS.attr('number'),
  maxType: DS.attr('string'),
  movementId: DS.belongsTo('movement')
});

```

However, with the above, my Ember app would not properly consume the Rails API serving the desired JSON:

```

// http://localhost:3000/movements

{
    "movements": [{
        "id": 1,
        "name": "foo",
        "movement type": "foo",
        "record_ids": [<record ids>] 
    } ... ],
    "records": [{
        "id": 1,
        "max effort": 123,
        "max type": "foo",
        "movement_id": <movement id> 
    } ... ]
}

```

But when I changed my model definitions to

```javascript

// app/models/movement.js
export default DS.Model.extend({
  ...
  records: DS.hasMany('record')
});

// app/models/record.js
export default DS.Model.extend({
  ...
  movement: DS.belongsTo('movement')
});

```

...everything now works as expected :)

**Note:** Just to be thorough, my Ember app has the records route nested for nested UI purposes, so initially movements were loaded fine but records weren't.

I solved this for myself by looking at the source for [Hummingbird](https://github.com/hummingbird-me/hummingbird).

So,  should the Ember property names for relationships not include Id/Ids on the end when using DS.ActiveModelAdapter? Seems to me to be the case. Unless I'm missing something.

If I'm right, I can make a pull request.

**Comment by andycrum** [comment]
Hey Mason, thanks for reporting this. It looks like you're correct! The properties themselves should just be the name of the related models (without 'id'). Will submit a fix for this ASAP.
