### ISSUE TITLE
JSON API support

### ISSUE THREAD

**Issue by knownasilya** [andycrum/ember-data-model-maker#15]
Since Ember Data is going JSON API by default, this might be necessary for this app to stay useful.

**Comment by andycrum** [comment]
Yeah, there's a WIP PR (#14) that @locks opened, but not much action on it since opening. Still trying to find time to do it myself.

**Comment by locks** [comment]
Sorry, got sidetracked!

**Comment by kedano** [comment]
Any progress on this? Love the current version of the tool, but I need to visualise the data for a fresh  Ember 2.0 app...

**Comment by locks** [comment]
@kedano I keep having to put out some other fires, but I've scheduled some ED this weekend so I'll try to fit this in. If you're able to help ping me on the Slack community.

**Comment by kedano** [comment]
@locks I forked the code and had a peek, but I'm too novice with Ember to contribute.

**Comment by andycrum** [comment]
I'm hoping to be able to get to this in the next week. Sorry for how long it's been... Things have been busy :(. I'm also on the Ember Slack, so let me know if you guys have any questions/comments.

**Comment by locks** [comment]
Pushed some more stuff to https://github.com/andycrum/ember-data-model-maker/pull/14. Now to try and actually add the JSONAPI format!
